### PR TITLE
Add support of load balancing methods (available in the free nginx ed.) in upstream sections

### PR DESCRIPTION
**Pull request by eluck**
According to http://web.archive.org/web/20150706124808/http://nginx.org/en/docs/http/ngx_http_upstream_module.html

[Review on Reviewable](https://reviewable.io/reviews/zxqfox/nginx-conf-parser/1)

### CODE REVIEW

**Comment by qfox** [comment]
Thanks!

**Comment by eluck** [comment]
@zxqfox Thanks! Your project is a great effort - lots of stuff to learn from (the regexp system is awesome). I wish includes were more meaningful :)

**Comment by qfox** [comment]
Thanks again, and feel free ;-)
I've added you to collaborators, just let me know if you want to publish to npm, I'll add you there.

**Comment by eluck** [comment]
Sure, thanks.

**Pull request merged**
